/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Dayanna
 */
public class GestionarRecetas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestionarRecetas.class.getName());
    private javax.swing.table.DefaultTableModel modeloTabla;
    private java.util.List<modelo.entidad.Receta> listaIngredientesTemp;

    /**
     * Creates new form GestionarProveedores
     */
    public GestionarRecetas() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        listaIngredientesTemp = new java.util.ArrayList<>();
        
        // Métodos de inicio
        configurarTabla();
        cargarCombos();
        estilizarVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbProducto = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbInsumo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIngredientes = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(222, 184, 135));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Configurar Receta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Seleccionar Producto:");

        cbProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProductoActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar Ingredientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Insumo:");

        cbInsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbInsumoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cantidad:");

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnQuitar.setText("Quitar");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        tblIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Insumo", "Cantidad", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblIngredientes);

        btnGuardar.setBackground(new java.awt.Color(46, 204, 113));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setText("Guardar Receta");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(cbInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(46, 46, 46)
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(172, 172, 172)
                            .addComponent(btnAgregar)
                            .addGap(75, 75, 75)
                            .addComponent(btnQuitar))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuitar)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarTabla() {
        String[] columnas = {"ID Insumo", "Insumo", "Cantidad Necesaria", "Unidad"};
        modeloTabla = new javax.swing.table.DefaultTableModel(null, columnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblIngredientes.setModel(modeloTabla);
    }

    // Llena los combos desde la base de datos
    private void cargarCombos() {
        controlador.ProductoCtrl prodCtrl = new controlador.ProductoCtrl();
        java.util.List<modelo.entidad.Producto> productos = prodCtrl.listarProductos();
        cbProducto.removeAllItems();
        for (modelo.entidad.Producto p : productos) {
            cbProducto.addItem(p); 
        }

        controlador.InsumoCtrl insumoCtrl = new controlador.InsumoCtrl();
        java.util.List<modelo.entidad.Insumo> insumos = insumoCtrl.listarInsumos();
        cbInsumo.removeAllItems();
        for (modelo.entidad.Insumo i : insumos) {
            cbInsumo.addItem(i);
        }
    }
    
    // Si seleccionas un producto que ya tiene receta, la muestra
    private void cargarRecetaExistente() {
        modelo.entidad.Producto prod = (modelo.entidad.Producto) cbProducto.getSelectedItem();
        if (prod == null) return;
        
        controlador.RecetaCtrl ctrl = new controlador.RecetaCtrl();
        java.util.List<modelo.entidad.Receta> recetaBD = ctrl.obtenerReceta(prod.getId_producto());
        
        listaIngredientesTemp.clear();
        modeloTabla.setRowCount(0);
        
        for (modelo.entidad.Receta r : recetaBD) {
            listaIngredientesTemp.add(r);
            agregarFilaTabla(r);
        }
    }
    
    private void agregarFilaTabla(modelo.entidad.Receta r) {
        modeloTabla.addRow(new Object[]{
            r.getInsumo().getId_insumo(),
            r.getInsumo().getNombre(),
            r.getCantidad_necesaria(),
            r.getInsumo().getUnidad_medida()
        });
    }
    
    private void estilizarVentana() {
        // 1. Fondo Crema muy suave (Para que parezca un recetario)
        this.getContentPane().setBackground(new java.awt.Color(255, 250, 240)); // Floral White
        
        // 2. Título "Chocolate"
        lblTitulo.setForeground(new java.awt.Color(139, 69, 19)); // Saddle Brown
        lblTitulo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 22));
        
        // 3. Labels
        jLabel2.setForeground(new java.awt.Color(100, 50, 0)); // Marrón oscuro
        
        // 4. Panel de "Agregar Ingredientes"
        jPanel1.setBackground(new java.awt.Color(255, 255, 255)); // Blanco puro
        
        // 5. Estilo de la Tabla (Encabezado "Cappuccino")
        javax.swing.table.JTableHeader header = tblIngredientes.getTableHeader();
        header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
        
        // Color de Fondo: Marrón claro (Tan/Trigo)
        header.setBackground(new java.awt.Color(222, 184, 135)); // Burlywood
        header.setForeground(new java.awt.Color(50, 30, 10));    // Texto Café
        header.setOpaque(false);
        
        // Borde inferior
        header.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(160, 82, 45))); // Sienna

        tblIngredientes.setRowHeight(28);
        tblIngredientes.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        // Selección: Crema oscuro
        tblIngredientes.setSelectionBackground(new java.awt.Color(255, 228, 196)); // Bisque
        tblIngredientes.setSelectionForeground(java.awt.Color.BLACK);
        tblIngredientes.setGridColor(new java.awt.Color(245, 222, 179)); // Wheat
        
        // Arreglar el fondo blanco del scroll
        if (tblIngredientes.getParent() != null && tblIngredientes.getParent().getParent() instanceof javax.swing.JScrollPane) {
            javax.swing.JScrollPane scroll = (javax.swing.JScrollPane) tblIngredientes.getParent().getParent();
            scroll.getViewport().setBackground(java.awt.Color.WHITE);
            scroll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(222, 184, 135)));
        }
        
        // 6. Botones (Temáticos)
        
        // Agregar: Azul (Acción neutra)
        colorearBoton(btnAgregar, new java.awt.Color(70, 130, 180)); // Steel Blue
        
        // Quitar: Rojo Terracota (Más elegante que rojo puro)
        colorearBoton(btnQuitar, new java.awt.Color(205, 92, 92));   // Indian Red
        
        // GUARDAR: Verde Oliva / Pasto (Acción final)
        colorearBoton(btnGuardar, new java.awt.Color(85, 107, 47));  // Dark Olive Green
    }
    
    // Método auxiliar para no repetir código
    private void colorearBoton(javax.swing.JButton btn, java.awt.Color color) {
        btn.setBackground(color);
        btn.setForeground(java.awt.Color.WHITE);
        btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        btn.setBorderPainted(false);
        btn.setFocusPainted(false);
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        
        // Efecto Hover simple
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn.setBackground(color.darker());
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn.setBackground(color);
            }
        });
    }
    
    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void cbInsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbInsumoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbInsumoActionPerformed

    private void cbProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProductoActionPerformed
        cargarRecetaExistente();
    }//GEN-LAST:event_cbProductoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        modelo.entidad.Insumo insumo = (modelo.entidad.Insumo) cbInsumo.getSelectedItem();
        String cantStr = txtCantidad.getText();

        if (insumo == null) return;

        try {
            double cantidad = Double.parseDouble(cantStr);
            if (cantidad <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Cantidad debe ser mayor a 0.");
                return;
            }

            // Evitar duplicados
            for (modelo.entidad.Receta r : listaIngredientesTemp) {
                if (r.getInsumo().getId_insumo() == insumo.getId_insumo()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Ya está en la lista. Bórralo para editar.");
                    return;
                }
            }

            // Crear y agregar
            modelo.entidad.Receta r = new modelo.entidad.Receta();
            r.setInsumo(insumo);
            r.setCantidad_necesaria(cantidad);

            listaIngredientesTemp.add(r);
            agregarFilaTabla(r);

            txtCantidad.setText("");
            cbInsumo.requestFocus();

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un número válido.");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        int fila = tblIngredientes.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un ingrediente.");
            return;
        }
        listaIngredientesTemp.remove(fila);
        modeloTabla.removeRow(fila);
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        modelo.entidad.Producto prod = (modelo.entidad.Producto) cbProducto.getSelectedItem();
    
        if (prod == null || listaIngredientesTemp.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un producto y agregue ingredientes.");
            return;
        }

        int resp = javax.swing.JOptionPane.showConfirmDialog(this, 
                "¿Guardar receta para '" + prod.getNombre() + "'?", "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);

        if (resp == javax.swing.JOptionPane.YES_OPTION) {
            controlador.RecetaCtrl ctrl = new controlador.RecetaCtrl();
            if (ctrl.guardarReceta(prod.getId_producto(), listaIngredientesTemp)) {
                javax.swing.JOptionPane.showMessageDialog(this, "¡Receta guardada!");
                this.dispose();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar.");
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GestionarRecetas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JComboBox<Object> cbInsumo;
    private javax.swing.JComboBox<Object> cbProducto;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblIngredientes;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
